import requests
import time
import chess


def request_ai_move(url: str, board: chess.Board, retries: int = 5, delay: int = 1):
    payload = {
        "fen": board.fen,
    }

    while retries > 0:
        retries -= 1

        response = requests.post(url, data=payload)

        if response.status_code != 200:
            print(f"Request failed with code {response.status_code}! Retrying...")
            time.sleep(delay)
            continue

        try:
            move_san: str = response.json()["move"]
        except (requests.exceptions.JSONDecodeError, KeyError):
            print(f"Couldn't decode JSON sent by server! Retrying...")
            time.sleep(delay)
            continue

        try:
            move = board.parse_san(move_san)
        except ValueError:
            print("AI used invalid SAN notation for move!")
            time.sleep(delay)
            continue

        if move not in board.legal_moves:
            print("Move generated by AI is illegal!")
            time.sleep(delay)
            continue

        return move

    return None


def request_user_move(board: chess.Board):
    while True:
        move = input("Insert your next move: ")
        try:
            move = board.parse_uci(move)
        except ValueError:
            print("Invalid UCI notation of move!")
            continue

        if move not in board.legal_moves:
            print("Illegal move!")
            continue

        return move
